use serde::{Deserialize, Serialize};

#[derive(Deserialize)]
pub struct MQLTerminalVersion {
    pub terminal_version: i64,
    pub build: i64,
    pub build_date: String,
}

#[derive(Deserialize)]
pub struct MQLTerminalInfo {
    pub community_account: bool,
    pub community_connection: bool,
    pub connected: bool,
    pub dlls_allowed: bool,
    pub trade_allowed: bool,
    pub tradeapi_disabled: bool,
    pub email_enabled: bool,
    pub ftp_enabled: bool,
    pub notifications_enabled: bool,
    pub mqid: bool,
    pub build: i64,
    pub maxbars: i64,
    pub codepage: i64,
    pub ping_last: i64,
    pub community_balance: f64,
    pub retransmission: f64,
    pub company: String,
    pub name: String,
    pub language: String,
    pub path: String,
    pub data_path: String,
    pub commondata_path: String,
}

pub enum TerminalInfoProperty {
    CommunityAccount,
    CommunityConnection,
    Connected,
    DllsAllowed,
    TradeAllowed,
    TradeApiDisabled,
    EmailEnabled,
    FtpEnabled,
    NotificationsEnabled,
    MqId,
    Build,
    MaxBars,
    CodePage,
    PingLast,
    CommunityBalance,
    Retransmission,
    Company,
    Name,
    Language,
    Path,
    DataPath,
    CommonDataPath,
}

#[derive(Deserialize)]
pub struct MQLAccountInfo {
    pub login: i64,
    pub trade_mode: i64,
    pub leverage: i64,
    pub limit_orders: i64,
    pub margin_so_mode: i64,
    pub trade_allowed: bool,
    pub trade_expert: bool,
    pub margin_mode: i64,
    pub currency_digits: i64,
    pub fifo_close: bool,
    pub balance: f64,
    pub credit: f64,
    pub profit: f64,
    pub equity: f64,
    pub margin: f64,
    pub margin_free: f64,
    pub margin_level: f64,
    pub margin_so_call: f64,
    pub margin_so_so: f64,
    pub margin_initial: f64,
    pub margin_maintenance: f64,
    pub assets: f64,
    pub liabilities: f64,
    pub commission_blocked: f64,
    pub name: String,
    pub server: String,
    pub currency: String,
    pub company: String,
}

#[derive(Serialize)]
pub struct MQLAccountCredentials {
    pub login: i64,
    pub password: String,
    pub server: String,
}

pub enum AccountInfoProperty {
    Login,
    TradeMode,
    Leverage,
    LimitOrders,
    MarginSoMode,
    TradeAllowed,
    TradeExpert,
    MarginMode,
    CurrencyDigits,
    FifoClose,
    Balance,
    Credit,
    Profit,
    Equity,
    Margin,
    MarginFree,
    MarginLevel,
    MarginSoCall,
    MarginSoSo,
    MarginInitial,
    MarginMaintenance,
    Assets,
    Liabilities,
    CommissionBlocked,
    Name,
    Server,
    Currency,
    Company,
}
